# Generated by Django 5.1 on 2024-09-30 15:44

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0004_branch_name_en_department_name_en'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BcsBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.IntegerField(default=10)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('title_en', models.CharField(blank=True, max_length=100, null=True, unique=True)),
            ],
            options={
                'ordering': ['serial'],
            },
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.IntegerField(default=10)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('title_en', models.CharField(blank=True, max_length=100, null=True, unique=True)),
            ],
            options={
                'ordering': ['serial'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.IntegerField(default=10)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('title_en', models.CharField(blank=True, max_length=100, null=True, unique=True)),
            ],
            options={
                'ordering': ['serial'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tid', models.IntegerField(default=10)),
                ('t_name', models.CharField(max_length=100)),
                ('t_name_bangla', models.CharField(blank=True, max_length=100, null=True)),
                ('t_email', models.EmailField(max_length=50, unique=True)),
                ('t_phone', models.CharField(max_length=11, unique=True)),
                ('service_id', models.CharField(max_length=25)),
                ('merit', models.CharField(blank=True, max_length=25, null=True)),
                ('t_date_of_birth', models.DateField(blank=True, null=True)),
                ('first_joining_date', models.DateField(blank=True, null=True)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('signature', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('message', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('message_en', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('bio', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('bio_en', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('batch', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.bcsbatch')),
                ('branch', models.ManyToManyField(blank=True, null=True, to='department.branch')),
                ('designation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.designation')),
                ('position', models.ManyToManyField(blank=True, null=True, to='teacher.position')),
                ('t_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='department.department')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['tid'],
            },
        ),
    ]
