# Generated by Django 5.2.4 on 2025-09-14 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.IntegerField(default=0)),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='কমিটির নাম (বাংলায়)')),
                ('title_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='Committee Name(English)')),
                ('created_at', models.DateField(blank=True, null=True, verbose_name='গঠনের তারিখ')),
                ('desolve_at', models.DateField(blank=True, null=True, verbose_name='মেয়াদের শেষ তারিখ')),
                ('is_active', models.BooleanField(default=False, verbose_name='সক্রিয় কিনা?')),
                ('convenor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='convenor', to='teacher.teacher', verbose_name='আহবায়ক')),
                ('member_secretary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_secretary', to='teacher.teacher', verbose_name='সদস্য সচিব')),
                ('position', models.ManyToManyField(blank=True, null=True, to='teacher.teacher', verbose_name='সদস্যগণ')),
            ],
            options={
                'ordering': ['serial'],
            },
        ),
    ]
