# Generated by Django 5.1 on 2024-10-04 02:35

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0005_alter_branch_options_alter_department_options_and_more'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='batch',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.bcsbatch', verbose_name='বিসিএস ব্যাচ'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='bio',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='জীবনী (বাংলা)'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='bio_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='জীবনী ইংরেজি'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='branch',
            field=models.ManyToManyField(blank=True, null=True, to='department.branch', verbose_name='শাখা'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='designation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.designation', verbose_name='পদবী'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='first_joining_date',
            field=models.DateField(blank=True, null=True, verbose_name='প্রথম যোগদানের তারিখ'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='ছবি'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='সক্রিয় কিনা?'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='joining_date',
            field=models.DateField(blank=True, null=True, verbose_name='যোগদানের তারিখ'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='merit',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='মেরিট পজিশন'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='message',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='মেসেজ(বাংলা)'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='message_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='মেসেজ ইংরেজি'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='position',
            field=models.ManyToManyField(blank=True, null=True, to='teacher.position', verbose_name='পদ'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='release_date',
            field=models.DateField(blank=True, null=True, verbose_name='রিলিজের তারিখ'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='service_id',
            field=models.CharField(max_length=25, verbose_name='সার্ভিস আইডি'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='স্বাক্ষর'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='t_date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='জন্ম তারিখ'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='t_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='department.department', verbose_name='বিভাগ'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='t_email',
            field=models.EmailField(max_length=50, unique=True, verbose_name='ই-মেইল'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='t_name',
            field=models.CharField(max_length=100, verbose_name='নাম(ইংরেজি)'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='t_name_bangla',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='নাম (বাংলা)'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='t_phone',
            field=models.CharField(max_length=11, unique=True, verbose_name='মোবাইল নং'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='tid',
            field=models.IntegerField(default=10, verbose_name='পদক্রম'),
        ),
    ]
