# Generated by Django 5.2.4 on 2025-09-14 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
        ('teacher', '0002_committee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='committee',
            name='position',
        ),
        migrations.AddField(
            model_name='committee',
            name='members_employee',
            field=models.ManyToManyField(blank=True, null=True, to='employee.employee', verbose_name='সদস্যগণ(কর্মচারী)'),
        ),
        migrations.AddField(
            model_name='committee',
            name='members_teacher',
            field=models.ManyToManyField(blank=True, null=True, to='teacher.teacher', verbose_name='সদস্যগণ(শিক্ষক/কর্মকর্তা)'),
        ),
    ]
