# Generated by Django 5.1 on 2024-10-04 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_alter_teacher_batch_alter_teacher_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.bcsbatch', verbose_name='বিসিএস ব্যাচ'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='designation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.designation', verbose_name='পদবী'),
        ),
    ]
