# Generated by Django 5.1.3 on 2024-12-30 14:08

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_alter_teacher_batch_alter_teacher_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='bio',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='জীবনী (বাংলা)'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='bio_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='জীবনী ইংরেজি'),
        ),
    ]
