# Generated by Django 5.1.3 on 2025-07-20 21:49

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_alter_teacher_bio_alter_teacher_bio_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='bio',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='জীবনী (বাংলা)'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='bio_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='জীবনী ইংরেজি'),
        ),
    ]
