# Generated by Django 5.1 on 2024-09-06 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_student_group_alter_student_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='name_bangla',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='name_bangla',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='group',
            field=models.CharField(choices=[('1', 'বিজ্ঞান'), ('2', 'মানবিক'), ('3', 'ব্যবসা শিক্ষা')], default='1', max_length=25),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_category',
            field=models.CharField(choices=[('1', 'এইচএসসি'), ('2', 'অনার্স'), ('3', 'মাস্টার্স')], max_length=100),
        ),
    ]
