# Generated by Django 5.1 on 2024-09-10 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_student_date_of_birth_teacher_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='class_year',
            field=models.CharField(choices=[('1', '১ম বর্ষ'), ('2', '২য় বর্ষ'), ('3', '৩য় বর্ষ'), ('4', '৪র্থ বর্ষ'), ('5', '১ম পর্ব'), ('6', 'শেষ পর্ব'), ('7', 'পাশকৃত')], max_length=100),
        ),
    ]
