# Generated by Django 5.1 on 2024-09-10 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_student_class_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='date_of_birth',
            new_name='t_date_of_birth',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='department',
            new_name='t_department',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='email',
            new_name='t_email',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='name',
            new_name='t_name',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='name_bangla',
            new_name='t_name_bangla',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='phone',
            new_name='t_phone',
        ),
    ]
