# Generated by Django 5.1 on 2024-09-11 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_rename_date_of_birth_teacher_t_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='class_roll',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
