# Generated by Django 5.1 on 2024-09-30 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_bcsbatch_class_designation_group_position_session_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='student',
            name='class_year',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='student',
            name='group',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='position',
        ),
        migrations.RemoveField(
            model_name='student',
            name='session',
        ),
        migrations.RemoveField(
            model_name='student',
            name='department',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_category',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='t_department',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='user',
        ),
        migrations.DeleteModel(
            name='BcsBatch',
        ),
        migrations.DeleteModel(
            name='Class',
        ),
        migrations.DeleteModel(
            name='Designation',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='Position',
        ),
        migrations.DeleteModel(
            name='Session',
        ),
        migrations.DeleteModel(
            name='StudentCategory',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
