# Generated by Django 5.1 on 2024-11-21 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_transaction_email_transaction_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
