# Generated by Django 5.1.3 on 2024-11-23 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_transaction_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='tran_id',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
