# Generated by Django 5.1.3 on 2024-11-27 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_paymentpurpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='tran_purpose',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.paymentpurpose'),
        ),
    ]
