# Generated by Django 5.1 on 2024-08-23 06:05

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.IntegerField()),
                ('cname', models.CharField(max_length=200)),
                ('ctext', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('cimage', models.ImageField(blank=True, null=True, upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tid', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=11)),
                ('designation', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('service_id', models.CharField(max_length=25)),
                ('batch', models.CharField(max_length=25)),
                ('merit', models.CharField(blank=True, max_length=25, null=True)),
                ('department', models.CharField(max_length=100)),
                ('duty_branch', models.CharField(blank=True, max_length=150, null=True)),
                ('first_joining_date', models.DateField(blank=True, null=True)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('message', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('bio', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
    ]
