# Generated by Django 5.1.3 on 2025-07-25 17:24

import ckeditor.fields
import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.IntegerField()),
                ('cname', models.CharField(max_length=200)),
                ('cname_en', models.CharField(blank=True, max_length=200, null=True)),
                ('ctext', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('ctext_en', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('cimage', models.ImageField(blank=True, null=True, upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('name_en', models.CharField(blank=True, max_length=100, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.IntegerField(default=10)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('title_en', models.CharField(max_length=100, unique=True)),
                ('address', models.CharField(max_length=100, unique=True)),
                ('address_en', models.CharField(max_length=100, unique=True)),
                ('slogan', models.CharField(max_length=100, unique=True)),
                ('slogan_en', models.CharField(max_length=100, unique=True)),
                ('eiin_no', models.CharField(max_length=25, unique=True)),
            ],
            options={
                'ordering': ['serial'],
            },
        ),
        migrations.CreateModel(
            name='NavElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.IntegerField(default=10)),
                ('head', models.CharField(max_length=100, unique=True)),
                ('head_en', models.CharField(blank=True, max_length=100, null=True, unique=True)),
            ],
            options={
                'ordering': ['serial'],
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('title_en', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('body_en', models.TextField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='media/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('published', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('name_en', models.CharField(blank=True, max_length=100, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('directory', models.CharField(blank=True, max_length=25, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NavItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.IntegerField(default=10)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('name_en', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('navelement', models.ManyToManyField(blank=True, null=True, to='frontpage.navelement')),
            ],
            options={
                'ordering': ['serial'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.IntegerField(default=10)),
                ('heading', models.CharField(blank=True, max_length=100, null=True)),
                ('heading_en', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('title_en', models.CharField(blank=True, max_length=500, null=True, unique=True)),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('body_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('type', models.CharField(choices=[('1', 'static'), ('2', 'dynamic'), ('3', 'link'), ('4', 'department')], default='1', max_length=25)),
                ('link', models.CharField(blank=True, max_length=500, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('category', models.ManyToManyField(blank=True, null=True, to='frontpage.category')),
                ('tag', models.ManyToManyField(blank=True, null=True, to='frontpage.tag')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='frontpage.template')),
            ],
            options={
                'ordering': ['serial'],
            },
        ),
        migrations.AddField(
            model_name='navelement',
            name='page',
            field=models.ManyToManyField(blank=True, null=True, to='frontpage.page'),
        ),
        migrations.CreateModel(
            name='ServiceBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.IntegerField(default=10)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('title_en', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('element', models.ManyToManyField(blank=True, null=True, to='frontpage.page')),
            ],
            options={
                'ordering': ['serial'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.IntegerField(default=10)),
                ('heading', models.CharField(blank=True, max_length=100, null=True)),
                ('heading_en', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('title_en', models.CharField(blank=True, max_length=500, null=True, unique=True)),
                ('body', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('body_en', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='media/')),
                ('link', models.CharField(blank=True, max_length=500, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('published', models.BooleanField(default=False)),
                ('category', models.ManyToManyField(blank=True, null=True, to='frontpage.category')),
                ('tag', models.ManyToManyField(blank=True, null=True, to='frontpage.tag')),
            ],
            options={
                'ordering': ['serial'],
            },
        ),
    ]
