# Generated by Django 5.1 on 2024-08-23 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='teacher',
            name='designation',
            field=models.CharField(choices=[('1', 'অধ্যাপক'), ('2', 'সহযোগী অধ্যাপক'), ('3', 'সহকারী অধ্যাপক'), ('4', 'প্রভাষক'), ('5', 'প্রদর্শক'), ('6', 'শরীরচর্চা শিক্ষক'), ('7', 'শিক্ষক'), ('8', 'প্রদর্শক(অনিয়মিত)')], default='4', max_length=100),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='position',
            field=models.CharField(choices=[('1', 'অধ্যক্ষ'), ('2', 'উপাধ্যক্ষ'), ('4', 'সম্পাদক (শিক্ষক পরিষদ)'), ('3', 'বিভাগীয় প্রধান')], default='4', max_length=100),
        ),
    ]
