# Generated by Django 5.1 on 2024-08-23 16:35

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0004_branch_remove_teacher_duty_branch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='NavItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('navelement', models.ManyToManyField(blank=True, null=True, to='frontpage.navelement')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('category', models.ManyToManyField(blank=True, null=True, to='frontpage.category')),
                ('tag', models.ManyToManyField(blank=True, null=True, to='frontpage.tag')),
            ],
        ),
        migrations.AddField(
            model_name='navelement',
            name='page',
            field=models.ManyToManyField(blank=True, null=True, to='frontpage.page'),
        ),
    ]
