# Generated by Django 5.1 on 2024-08-24 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0006_notice_remove_navelement_page_servicebox_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicebox',
            name='element',
        ),
        migrations.AddField(
            model_name='servicebox',
            name='element',
            field=models.ManyToManyField(blank=True, null=True, to='frontpage.page'),
        ),
    ]
