# Generated by Django 5.1 on 2024-08-24 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0008_rename_head_navelement_title_remove_navelement_page_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='navelement',
            old_name='title',
            new_name='head',
        ),
    ]
