# Generated by Django 5.1 on 2024-08-24 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0009_rename_title_navelement_head'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
