# Generated by Django 5.1 on 2024-08-24 05:05

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0010_alter_notice_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='heading',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(max_length=500)),
                ('body', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('category', models.ManyToManyField(blank=True, null=True, to='frontpage.category')),
                ('tag', models.ManyToManyField(blank=True, null=True, to='frontpage.tag')),
            ],
        ),
    ]
