# Generated by Django 5.1 on 2024-08-24 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0011_page_heading_alter_page_title_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
