# Generated by Django 5.1 on 2024-08-27 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0014_template_page_date_page_published_page_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
