# Generated by Django 5.1 on 2024-08-30 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0015_page_link_post_file_teacher_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='type',
            field=models.CharField(choices=[('1', 'static'), ('2', 'dynamic'), ('3', 'link')], default='1', max_length=25),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='position',
            field=models.CharField(choices=[('1', 'অধ্যক্ষ'), ('2', 'উপাধ্যক্ষ'), ('3', 'সম্পাদক (শিক্ষক পরিষদ)'), ('4', 'বিভাগীয় প্রধান'), ('5', 'শিক্ষক'), ('6', 'কর্মকর্তা'), ('7', 'অন্যান্য')], default='1', max_length=100),
        ),
    ]
