# Generated by Django 5.1 on 2024-09-03 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0017_branch_serial_department_serial_navelement_serial_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='navelement',
            options={'ordering': ['serial']},
        ),
        migrations.AlterModelOptions(
            name='navitem',
            options={'ordering': ['serial']},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['serial']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['serial']},
        ),
    ]
