# Generated by Django 5.1 on 2024-09-04 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0003_branch_department_delete_student'),
        ('frontpage', '0018_alter_navelement_options_alter_navitem_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='department',
        ),
        migrations.DeleteModel(
            name='Branch',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
