# Generated by Django 5.1.3 on 2024-12-30 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0021_institute_carousel_cname_en_carousel_ctext_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
