# Generated by Django 5.1 on 2025-07-20 07:18

import frontpage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0021_institute_carousel_cname_en_carousel_ctext_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=frontpage.models.get_file_path),
        ),
    ]
