# Generated by Django 5.1.3 on 2025-07-20 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0022_alter_post_file'),
        ('frontpage', '0022_post_link'),
    ]

    operations = [
    ]
