# Generated by Django 5.1.3 on 2025-07-20 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0023_merge_0022_alter_post_file_0022_post_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='link',
        ),
    ]
