# Generated by Django 5.1.3 on 2025-07-25 17:24

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.IntegerField(default=10)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('title_en', models.CharField(blank=True, max_length=100, null=True, unique=True)),
            ],
            options={
                'ordering': ['serial'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.IntegerField(default=10)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('title_en', models.CharField(blank=True, max_length=100, null=True, unique=True)),
            ],
            options={
                'ordering': ['serial'],
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.IntegerField(default=10)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('title_en', models.CharField(blank=True, max_length=100, null=True, unique=True)),
            ],
            options={
                'ordering': ['serial'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.IntegerField(default=10, verbose_name='পদক্রম')),
                ('employee_name', models.CharField(max_length=100, verbose_name='নাম(ইংরেজি)')),
                ('employee_name_bangla', models.CharField(blank=True, max_length=100, null=True, verbose_name='নাম (বাংলা)')),
                ('employee_email', models.EmailField(max_length=50, unique=True, verbose_name='ই-মেইল')),
                ('employee_phone', models.CharField(max_length=11, unique=True, verbose_name='মোবাইল নং')),
                ('service_id', models.CharField(max_length=25, verbose_name='সার্ভিস আইডি')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='জন্ম তারিখ')),
                ('first_joining_date', models.DateField(blank=True, null=True, verbose_name='প্রথম যোগদানের তারিখ')),
                ('joining_date', models.DateField(blank=True, null=True, verbose_name='যোগদানের তারিখ')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='রিলিজের তারিখ')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='ছবি')),
                ('signature', models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='স্বাক্ষর')),
                ('bio', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='জীবনী (বাংলা)')),
                ('bio_en', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='জীবনী ইংরেজি')),
                ('is_active', models.BooleanField(default=False, verbose_name='সক্রিয় কিনা?')),
                ('branch', models.ManyToManyField(blank=True, null=True, to='department.branch', verbose_name='শাখা')),
                ('designation', models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.designation', verbose_name='পদবী')),
                ('employee_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='department.department', verbose_name='বিভাগ')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('position', models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.position', verbose_name='পদ')),
                ('employee_type', models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.type', verbose_name='কর্মচারীর ধরণ')),
            ],
            options={
                'ordering': ['serial'],
            },
        ),
    ]
