# Generated by Django 5.1.3 on 2024-12-07 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='emloyee_department',
            new_name='employee_department',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='emloyee_email',
            new_name='employee_email',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='emloyee_name',
            new_name='employee_name',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='emloyee_name_bangla',
            new_name='employee_name_bangla',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='emloyee_phone',
            new_name='employee_phone',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='emloyee_type',
            new_name='employee_type',
        ),
    ]
