# Generated by Django 5.1.3 on 2024-12-07 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_rename_emloyee_department_employee_employee_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.IntegerField(default=10)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('title_en', models.CharField(blank=True, max_length=100, null=True, unique=True)),
            ],
            options={
                'ordering': ['serial'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.IntegerField(default=10)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('title_en', models.CharField(blank=True, max_length=100, null=True, unique=True)),
            ],
            options={
                'ordering': ['serial'],
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.IntegerField(default=10)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('title_en', models.CharField(blank=True, max_length=100, null=True, unique=True)),
            ],
            options={
                'ordering': ['serial'],
            },
        ),
        migrations.AlterField(
            model_name='employee',
            name='designation',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.designation', verbose_name='পদবী'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.position', verbose_name='পদ'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_type',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.type', verbose_name='কর্মচারীর ধরণ'),
        ),
    ]
