# Generated by Django 5.1 on 2024-11-18 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
        ('payment', '0002_transaction_email_transaction_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.transaction'),
        ),
    ]
