# Generated by Django 5.1.3 on 2024-11-19 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_alter_certificate_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='email',
            field=models.EmailField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='phone',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
