# Generated by Django 5.1.3 on 2024-11-22 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0003_alter_certificate_email_alter_certificate_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='certificate_type',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
