# Generated by Django 5.1.3 on 2025-07-25 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
                ('name_en', models.CharField(max_length=15, unique=True)),
                ('link', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GuardianInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.IntegerField(default=10)),
                ('father_name', models.CharField(blank=True, max_length=100, null=True)),
                ('father_name_en', models.CharField(blank=True, max_length=100, null=True)),
                ('profession_of_father', models.CharField(blank=True, max_length=25, null=True)),
                ('father_nid', models.CharField(blank=True, max_length=25, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=100, null=True)),
                ('mother_name_en', models.CharField(blank=True, max_length=100, null=True)),
                ('profession_of_mother', models.CharField(blank=True, max_length=25, null=True)),
                ('mother_nid', models.CharField(blank=True, max_length=100, null=True)),
                ('guardian_phone', models.CharField(blank=True, max_length=11, null=True)),
                ('anual_income', models.CharField(blank=True, max_length=11, null=True)),
            ],
            options={
                'ordering': ['serial'],
            },
        ),
        migrations.CreateModel(
            name='StudentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.IntegerField(default=10)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('title_en', models.CharField(blank=True, max_length=100, null=True, unique=True)),
            ],
            options={
                'ordering': ['serial'],
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
                ('name_en', models.CharField(max_length=25, unique=True)),
                ('lattitude', models.CharField(blank=True, max_length=15, null=True)),
                ('longitude', models.CharField(blank=True, max_length=15, null=True)),
                ('link', models.CharField(blank=True, max_length=15, null=True)),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.division')),
            ],
            options={
                'ordering': ['name_en'],
            },
        ),
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.IntegerField(default=10)),
                ('village_or_house', models.CharField(blank=True, max_length=50, null=True)),
                ('house_or_street_no', models.CharField(blank=True, max_length=25, null=True)),
                ('post_office', models.CharField(blank=True, max_length=25, null=True)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.district')),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.division')),
            ],
            options={
                'ordering': ['serial'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_id', models.IntegerField(default=10)),
                ('name', models.CharField(max_length=100)),
                ('name_bangla', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.CharField(max_length=11)),
                ('class_roll', models.CharField(blank=True, max_length=11, null=True)),
                ('section', models.CharField(blank=True, max_length=25, null=True)),
                ('exam_roll', models.CharField(blank=True, max_length=25, null=True)),
                ('registration', models.CharField(blank=True, max_length=25, null=True)),
                ('cgpa', models.CharField(blank=True, max_length=15, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=15, null=True)),
                ('passing_year', models.CharField(blank=True, max_length=25, null=True)),
                ('nationality', models.CharField(blank=True, max_length=15, null=True)),
                ('birth_registration', models.CharField(blank=True, max_length=25, null=True)),
                ('religion', models.CharField(blank=True, max_length=15, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=10, null=True)),
                ('marital_status', models.CharField(blank=True, max_length=25, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('signature', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('is_active', models.BooleanField(default=False)),
                ('class_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='department.class')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='department.department')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='department.group')),
                ('guardian_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.guardianinfo')),
                ('permanent_adress', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permanent_adress', to='student.adress')),
                ('present_adress', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='present_adress', to='student.adress')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='department.session')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('student_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.studentcategory')),
            ],
        ),
        migrations.CreateModel(
            name='SscEquvalent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.IntegerField(default=10)),
                ('ssc_or_equvalent', models.CharField(blank=True, max_length=25, null=True)),
                ('ssc_board', models.CharField(blank=True, max_length=25, null=True)),
                ('ssc_exam_roll', models.CharField(blank=True, max_length=25, null=True)),
                ('ssc_regitration_no', models.CharField(blank=True, max_length=25, null=True)),
                ('ssc_cgpa_with_4th', models.CharField(blank=True, max_length=25, null=True)),
                ('ssc_cgpa_without_4th', models.CharField(blank=True, max_length=25, null=True)),
                ('ssc_passing_year', models.CharField(blank=True, max_length=25, null=True)),
                ('ssc_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='department.group')),
                ('ssc_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='department.session')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
            options={
                'ordering': ['serial'],
            },
        ),
        migrations.CreateModel(
            name='StudentAdmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.IntegerField(default=10)),
                ('ssc_roll', models.CharField(blank=True, max_length=25, null=True)),
                ('name', models.CharField(blank=True, max_length=125, null=True)),
                ('passing_year', models.CharField(blank=True, max_length=25, null=True)),
                ('board', models.CharField(blank=True, max_length=25, null=True)),
                ('group', models.CharField(blank=True, max_length=25, null=True)),
                ('quota', models.CharField(blank=True, max_length=25, null=True)),
                ('status', models.CharField(default='Not Admitted', max_length=100)),
                ('student', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.student')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SubjectChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.IntegerField(default=10)),
                ('compulsory_subject', models.ManyToManyField(blank=True, null=True, related_name='compulsory_subject', to='department.subject')),
                ('fourth_subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='department.subject')),
                ('optional_subject', models.ManyToManyField(blank=True, null=True, related_name='optional_subject', to='department.subject')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
            options={
                'ordering': ['serial'],
            },
        ),
        migrations.CreateModel(
            name='Upazilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('name_en', models.CharField(max_length=25)),
                ('link', models.CharField(blank=True, max_length=15, null=True)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.district')),
            ],
            options={
                'ordering': ['name_en'],
            },
        ),
        migrations.CreateModel(
            name='Union',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('name_en', models.CharField(max_length=25)),
                ('link', models.CharField(blank=True, max_length=15, null=True)),
                ('upazilla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.upazilla')),
            ],
            options={
                'ordering': ['name_en'],
            },
        ),
        migrations.AddField(
            model_name='adress',
            name='upazilla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.upazilla'),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.IntegerField(default=10)),
                ('phone', models.CharField(blank=True, max_length=11, null=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('transactionID', models.CharField(blank=True, max_length=25, null=True)),
                ('purpose', models.CharField(blank=True, max_length=25, null=True)),
                ('method', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.CharField(blank=True, max_length=25, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('refunded', models.BooleanField(default=False)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
            options={
                'ordering': ['serial'],
                'unique_together': {('student', 'transactionID')},
            },
        ),
    ]
