# Generated by Django 5.2.4 on 2025-07-17 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='link',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='division',
            name='name_en',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='union',
            name='link',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
    ]
