# Generated by Django 5.2.4 on 2025-07-17 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_division_link_alter_division_name_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='lattitude',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='district',
            name='link',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='district',
            name='longitude',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='upazilla',
            name='link',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
    ]
