# Generated by Django 5.1 on 2024-10-05 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_division'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
                ('name_en', models.CharField(max_length=25, unique=True)),
                ('lattitude', models.CharField(max_length=15, unique=True)),
                ('longitude', models.CharField(max_length=15, unique=True)),
                ('link', models.CharField(blank=True, max_length=15, null=True)),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.division')),
            ],
        ),
    ]
