# Generated by Django 5.2.4 on 2025-08-06 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_district_lattitude_alter_district_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='lattitude',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='district',
            name='link',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='district',
            name='longitude',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='division',
            name='link',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='division',
            name='name_en',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='union',
            name='link',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='upazilla',
            name='link',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
