# Generated by Django 5.1 on 2024-10-05 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_alter_district_lattitude_alter_district_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='union',
            name='name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='union',
            name='name_en',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='upazilla',
            name='name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='upazilla',
            name='name_en',
            field=models.CharField(max_length=25),
        ),
    ]
