# Generated by Django 5.1 on 2024-10-14 08:00

import django.db.models.deletion
import student.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0005_alter_branch_options_alter_department_options_and_more'),
        ('student', '0006_alter_union_name_alter_union_name_en_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuardianInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.IntegerField(default=10)),
                ('father_name', models.CharField(blank=True, max_length=100, null=True)),
                ('father_name_en', models.CharField(blank=True, max_length=100, null=True)),
                ('profession_of_father', models.CharField(blank=True, max_length=25, null=True)),
                ('father_nid', models.CharField(blank=True, max_length=25, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=100, null=True)),
                ('mother_name_en', models.CharField(blank=True, max_length=100, null=True)),
                ('profession_of_mother', models.CharField(blank=True, max_length=25, null=True)),
                ('mother_nid', models.CharField(blank=True, max_length=100, null=True)),
                ('guardian_phone', models.CharField(blank=True, max_length=11, null=True)),
                ('anual_income', models.CharField(blank=True, max_length=11, null=True)),
            ],
            options={
                'ordering': ['serial'],
            },
        ),
        migrations.AlterModelOptions(
            name='district',
            options={'ordering': ['division']},
        ),
        migrations.AlterModelOptions(
            name='division',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='union',
            options={'ordering': ['upazilla']},
        ),
        migrations.AlterModelOptions(
            name='upazilla',
            options={'ordering': ['district']},
        ),
        migrations.AddField(
            model_name='student',
            name='birth_registration',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='blood_group',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='marital_status',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='nationality',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='religion',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='section',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='class_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.class'),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='department.department'),
        ),
        migrations.AlterField(
            model_name='student',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.group'),
        ),
        migrations.AlterField(
            model_name='student',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.session'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.studentcategory'),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.IntegerField(default=10)),
                ('village_or_house', models.CharField(blank=True, max_length=50, null=True)),
                ('house_or_street_no', models.CharField(blank=True, max_length=25, null=True)),
                ('post_office', models.CharField(blank=True, max_length=25, null=True)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.district')),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.division')),
                ('upazilla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.upazilla')),
            ],
            options={
                'ordering': ['serial'],
            },
        ),
        migrations.AddField(
            model_name='student',
            name='permanent_adress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Permanent', to='student.adress'),
        ),
        migrations.AddField(
            model_name='student',
            name='present_adress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.adress'),
        ),
        migrations.AddField(
            model_name='student',
            name='guardian_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.guardianinfo'),
        ),
        migrations.CreateModel(
            name='SscEquvalent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.IntegerField(default=10)),
                ('ssc_or_equvalent', models.CharField(blank=True, max_length=25, null=True)),
                ('board', models.CharField(blank=True, max_length=25, null=True)),
                ('exam_roll', models.CharField(blank=True, max_length=25, null=True)),
                ('regitration_no', models.CharField(blank=True, max_length=25, null=True)),
                ('group', models.CharField(blank=True, max_length=25, null=True)),
                ('cgpa_with_4th', models.CharField(blank=True, max_length=25, null=True)),
                ('cgpa_without_4th', models.CharField(blank=True, max_length=25, null=True)),
                ('passing_year', models.IntegerField(blank=True, choices=student.models.year_choices, null=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.session')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
            options={
                'ordering': ['serial'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.IntegerField(default=10)),
                ('transactionID', models.CharField(blank=True, max_length=25, null=True)),
                ('purpose', models.CharField(blank=True, max_length=25, null=True)),
                ('method', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.CharField(blank=True, max_length=25, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('refunded', models.BooleanField(default=False)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
            options={
                'ordering': ['serial'],
                'unique_together': {('transactionID', 'method')},
            },
        ),
    ]
