# Generated by Django 5.1 on 2024-10-18 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_alter_transaction_unique_together_subjectchoice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='district',
            options={'ordering': ['name_en']},
        ),
        migrations.AlterModelOptions(
            name='union',
            options={'ordering': ['name_en']},
        ),
        migrations.AlterModelOptions(
            name='upazilla',
            options={'ordering': ['name_en']},
        ),
        migrations.AlterField(
            model_name='sscequvalent',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.group'),
        ),
    ]
