# Generated by Django 5.1 on 2024-10-19 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_alter_district_options_alter_union_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='class_year',
        ),
        migrations.RemoveField(
            model_name='sscequvalent',
            name='group',
        ),
        migrations.RemoveField(
            model_name='student',
            name='group',
        ),
        migrations.RemoveField(
            model_name='sscequvalent',
            name='session',
        ),
        migrations.RemoveField(
            model_name='student',
            name='session',
        ),
        migrations.RemoveField(
            model_name='student',
            name='department',
        ),
        migrations.RemoveField(
            model_name='subjectchoice',
            name='compulsory_subject',
        ),
        migrations.RemoveField(
            model_name='subjectchoice',
            name='fourth_subject',
        ),
        migrations.RemoveField(
            model_name='subjectchoice',
            name='optional_subject',
        ),
        migrations.DeleteModel(
            name='Class',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='Session',
        ),
    ]
