# Generated by Django 5.1 on 2024-10-19 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0007_alter_subject_type'),
        ('student', '0010_remove_student_class_year_remove_sscequvalent_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sscequvalent',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='department.group'),
        ),
        migrations.AddField(
            model_name='sscequvalent',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='department.session'),
        ),
        migrations.AddField(
            model_name='student',
            name='class_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='department.class'),
        ),
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='department.department'),
        ),
        migrations.AddField(
            model_name='student',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='department.group'),
        ),
        migrations.AddField(
            model_name='student',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='department.session'),
        ),
        migrations.AddField(
            model_name='subjectchoice',
            name='compulsory_subject',
            field=models.ManyToManyField(blank=True, null=True, related_name='compulsory_subject', to='department.subject'),
        ),
        migrations.AddField(
            model_name='subjectchoice',
            name='fourth_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='department.subject'),
        ),
        migrations.AddField(
            model_name='subjectchoice',
            name='optional_subject',
            field=models.ManyToManyField(blank=True, null=True, related_name='optional_subject', to='department.subject'),
        ),
    ]
