# Generated by Django 5.1 on 2024-10-28 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_sscequvalent_group_sscequvalent_session_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAdmissionStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.IntegerField(default=10)),
                ('ssc_roll', models.CharField(blank=True, max_length=25, null=True)),
                ('name', models.CharField(blank=True, max_length=125, null=True)),
                ('passing_year', models.CharField(blank=True, max_length=25, null=True)),
                ('board', models.CharField(blank=True, max_length=25, null=True)),
                ('group', models.CharField(blank=True, max_length=25, null=True)),
                ('quota', models.CharField(blank=True, max_length=25, null=True)),
            ],
            options={
                'ordering': ['serial'],
            },
        ),
    ]
