# Generated by Django 5.1 on 2024-10-28 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_studentadmissionstudent'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentAdmissionStudent',
            new_name='StudentAdmission',
        ),
    ]
