# Generated by Django 5.1 on 2024-10-28 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_rename_studentadmissionstudent_studentadmission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentadmission',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='studentadmission',
            name='status',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
