# Generated by Django 5.1 on 2024-11-02 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0016_rename_board_sscequvalent_ssc_board_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='cgpa',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
