# Generated by Django 5.1 on 2024-11-09 04:14

import student.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0017_student_cgpa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sscequvalent',
            name='ssc_passing_year',
            field=models.CharField(blank=True, choices=student.models.year_choices, max_length=25, null=True),
        ),
    ]
