# Generated by Django 5.1 on 2024-11-13 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0018_alter_sscequvalent_ssc_passing_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sscequvalent',
            name='ssc_passing_year',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='passing_year',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='permanent_adress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permanent_adress', to='student.adress'),
        ),
        migrations.AlterField(
            model_name='student',
            name='present_adress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='present_adress', to='student.adress'),
        ),
    ]
