# Generated by Django 5.1.3 on 2024-11-30 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0021_alter_student_email_alter_student_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentadmission',
            name='student',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.student'),
        ),
    ]
