# Generated by Django 5.1.3 on 2025-07-25 17:24

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('frontpage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.IntegerField(default=10)),
                ('code', models.CharField(blank=True, max_length=20, null=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('name_en', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['serial'],
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.IntegerField(default=10)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('title_en', models.CharField(blank=True, max_length=100, null=True, unique=True)),
            ],
            options={
                'ordering': ['serial'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.IntegerField(default=10)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('name_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name(In English)')),
                ('code', models.CharField(blank=True, max_length=20, null=True)),
                ('about', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('about_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='About(In English)')),
                ('professor', models.IntegerField(default=0)),
                ('associate_professor', models.IntegerField(default=0)),
                ('assistant_professor', models.IntegerField(default=0)),
                ('lecturer', models.IntegerField(default=0)),
                ('demonstrator', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['serial'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.IntegerField(default=10)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('title_en', models.CharField(blank=True, max_length=100, null=True, unique=True)),
            ],
            options={
                'ordering': ['serial'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.IntegerField(default=10)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('title_en', models.CharField(blank=True, max_length=100, null=True, unique=True)),
            ],
            options={
                'ordering': ['serial'],
            },
        ),
        migrations.CreateModel(
            name='NavDepartmentElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.IntegerField(default=10)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('title_en', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('body_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('type', models.CharField(choices=[('1', 'static'), ('2', 'dynamic'), ('3', 'link'), ('4', 'department')], default='1', max_length=25)),
                ('link', models.CharField(blank=True, max_length=500, null=True)),
                ('category', models.ManyToManyField(blank=True, null=True, to='frontpage.category')),
                ('department', models.ManyToManyField(blank=True, null=True, to='department.department')),
                ('tag', models.ManyToManyField(blank=True, null=True, to='frontpage.tag')),
            ],
            options={
                'ordering': ['serial'],
            },
        ),
        migrations.CreateModel(
            name='NavDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.IntegerField(default=10)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('title_en', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('link', models.CharField(blank=True, max_length=500, null=True)),
                ('department', models.ManyToManyField(blank=True, null=True, to='department.department')),
                ('element', models.ManyToManyField(blank=True, null=True, to='department.navdepartmentelement')),
            ],
            options={
                'ordering': ['serial'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.IntegerField(default=10)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('name_en', models.CharField(blank=True, max_length=100, null=True)),
                ('code', models.CharField(blank=True, max_length=20, null=True)),
                ('type', models.CharField(blank=True, max_length=25, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('department', models.ManyToManyField(blank=True, null=True, to='department.department')),
                ('group', models.ManyToManyField(blank=True, null=True, to='department.group')),
            ],
            options={
                'ordering': ['serial'],
            },
        ),
    ]
