# Generated by Django 5.1 on 2024-08-30 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('frontpage', '0016_alter_page_type_alter_teacher_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=11)),
                ('class_roll', models.CharField(max_length=11)),
                ('session', models.CharField(choices=[('1', '2022-23'), ('2', '2023-24'), ('3', '2024-25'), ('4', '2025-26'), ('5', '2026-27'), ('6', '2027-28 '), ('7', '2028-29'), ('8', '2029-30')], default='4', max_length=100)),
                ('student_category', models.CharField(choices=[('1', 'এইচএসসি'), ('2', 'অনার্স'), ('3', 'মাস্টার্স')], default='1', max_length=100)),
                ('exam_roll', models.CharField(max_length=25)),
                ('registration', models.CharField(max_length=25)),
                ('class_year', models.CharField(choices=[('1', '১ম বর্ষ'), ('2', '২য় বর্ষ'), ('3', '৩য় বর্ষ'), ('4', '৪র্থ বর্ষ'), ('5', '১ম পর্ব'), ('6', 'শেষ পর্ব'), ('7', 'পাশকৃত')], default='1', max_length=100)),
                ('passing_year', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('signature', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='frontpage.department')),
            ],
        ),
    ]
