# Generated by Django 5.1 on 2024-08-30 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='exam_roll',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='registration',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
