# Generated by Django 5.1 on 2024-10-19 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0006_class_group_session_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='type',
            field=models.CharField(blank=True, choices=[('Non-Major', 'Non-Major'), ('Compulsory', 'Compulsory'), ('Optional', 'Optional'), ('Major', 'Major')], max_length=25, null=True),
        ),
    ]
