# Generated by Django 5.1 on 2024-10-31 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0010_alter_subject_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='type',
            field=models.CharField(blank=True, choices=[('Major', 'Major'), ('Compulsory', 'Compulsory'), ('Fourth', 'Fourth'), ('Optional', 'Optional'), ('Non-Major', 'Non-Major')], max_length=25, null=True),
        ),
    ]
