# Generated by Django 5.1 on 2024-10-31 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0011_alter_subject_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='type',
            field=models.CharField(blank=True, choices=[('Optional', 'Optional'), ('Fourth', 'Fourth'), ('Compulsory', 'Compulsory'), ('Non-Major', 'Non-Major'), ('Major', 'Major')], max_length=25, null=True),
        ),
    ]
