# Generated by Django 5.1 on 2024-10-31 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0012_alter_subject_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='type',
            field=models.CharField(blank=True, choices=[('Compulsory', 'Compulsory'), ('Optional', 'Optional'), ('Non-Major', 'Non-Major'), ('Major', 'Major'), ('Fourth', 'Fourth')], max_length=25, null=True),
        ),
    ]
