# Generated by Django 5.1 on 2024-11-02 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0013_alter_subject_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='type',
            field=models.CharField(blank=True, choices=[('Non-Major', 'Non-Major'), ('Optional', 'Optional'), ('Major', 'Major'), ('Fourth', 'Fourth'), ('Compulsory', 'Compulsory')], max_length=25, null=True),
        ),
    ]
