# Generated by Django 5.1.3 on 2024-11-15 02:31

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0017_alter_subject_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='about',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='about_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='type',
            field=models.CharField(blank=True, choices=[('Compulsory', 'Compulsory'), ('Major', 'Major'), ('Optional', 'Optional'), ('Fourth', 'Fourth'), ('Non-Major', 'Non-Major')], max_length=25, null=True),
        ),
    ]
