# Generated by Django 5.1.3 on 2024-11-15 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0018_department_about_department_about_en_and_more'),
        ('frontpage', '0021_institute_carousel_cname_en_carousel_ctext_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='type',
            field=models.CharField(blank=True, choices=[('Optional', 'Optional'), ('Compulsory', 'Compulsory'), ('Fourth', 'Fourth'), ('Major', 'Major'), ('Non-Major', 'Non-Major')], max_length=25, null=True),
        ),
        migrations.CreateModel(
            name='NavDepartmentElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.IntegerField(default=10)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('title_en', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('type', models.CharField(choices=[('1', 'static'), ('2', 'dynamic'), ('3', 'link'), ('4', 'department')], default='1', max_length=25)),
                ('link', models.CharField(blank=True, max_length=500, null=True)),
                ('category', models.ManyToManyField(blank=True, null=True, to='frontpage.category')),
                ('tag', models.ManyToManyField(blank=True, null=True, to='frontpage.tag')),
            ],
            options={
                'ordering': ['serial'],
            },
        ),
        migrations.CreateModel(
            name='NavDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.IntegerField(default=10)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('title_en', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('link', models.CharField(blank=True, max_length=500, null=True)),
                ('element', models.ManyToManyField(blank=True, null=True, to='department.navdepartmentelement')),
            ],
            options={
                'ordering': ['serial'],
            },
        ),
    ]
