# Generated by Django 5.1.3 on 2024-11-15 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0019_alter_subject_type_navdepartmentelement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='navdepartment',
            name='department',
            field=models.ManyToManyField(blank=True, null=True, to='department.department'),
        ),
        migrations.AddField(
            model_name='navdepartmentelement',
            name='department',
            field=models.ManyToManyField(blank=True, null=True, to='department.department'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='type',
            field=models.CharField(blank=True, choices=[('Major', 'Major'), ('Non-Major', 'Non-Major'), ('Optional', 'Optional'), ('Compulsory', 'Compulsory'), ('Fourth', 'Fourth')], max_length=25, null=True),
        ),
    ]
