# Generated by Django 5.1.3 on 2024-11-15 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0020_navdepartment_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='type',
            field=models.CharField(blank=True, choices=[('Major', 'Major'), ('Fourth', 'Fourth'), ('Compulsory', 'Compulsory'), ('Non-Major', 'Non-Major'), ('Optional', 'Optional')], max_length=25, null=True),
        ),
    ]
