# Generated by Django 5.1.3 on 2024-11-15 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0023_navdepartmentelement_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='type',
            field=models.CharField(blank=True, choices=[('Non-Major', 'Non-Major'), ('Fourth', 'Fourth'), ('Compulsory', 'Compulsory'), ('Optional', 'Optional'), ('Major', 'Major')], max_length=25, null=True),
        ),
    ]
