# Generated by Django 5.1 on 2024-11-18 07:25

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0028_alter_subject_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='about_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='About(In English)'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Name(In English)'),
        ),
    ]
